import 'package:flutter/material.dart';

class AppColors {
  static const Color primary = Color(0xFF3E9452);
  static const Color backgroundColor = Color(0xFFF0F0EC);
  static const Color backgroundColor2 = Color(0xFFF2F2ED);
  static const Color secondary = Color(0xFFF2F2F2);
  static const Color signUpTextButtonRadius = Color(0xFF979797);
  static const Color signText1 = Color(0xFF000000);
  static const Color lightBlack = Color(0xFF252525);
  static const Color searchBoxText = Color(0xFF8A96BC);
  static const Color drNameText = Color(0xFF222B45);
  static const Color bottomText = Color(0xFF393939);
  static const Color bottomTextfield = Color(0xFF929292);
  static const Color bottomTextfieldText = Color(0xFF4F4F4F);
  static const Color reviewText = Color(0xFF6B779A);
  static const Color searchIcon = Color(0xFF8a96bc);
  static const Color drList = Color(0xFF263257);
  static const Color searchScreenRating = Color(0xFFfbc723);
  static const Color bottomText1 = Color(0xFF4A4A4A);
  static const Color drContainer = Color(0xFFF7F8F8);
  static const Color tp = Color(0xFFFFFFFF);
  static const Color filterText = Color(0xFFBABABC);
  static const Color notificationText = Color(0xFF6C6C6C);
  static const Color drRating = Color(0xFFD87234);
  static const Color drPatients = Color(0xFF7ACEFA);
  static const Color drExperience = Color(0xFFFDF1F3);
  static const Color drRatings = Color(0xFFFEF6EC);
  static const Color drRatingsIcon = Color(0xFFF7C480);
  static const Color waring = Color(0xFFFE0F0A);
  static const Color waring1 = Color(0xFFFF0000);
  static const Color headLine = Color(0xFF1C2A3A);
  static const Color hospitalText = Color(0xFF4B5563);
  static const Color hospitalLocationText = Color(0xFF6B7280);
  static const Color patientsContainer = Color(0xFFb5b5b5);
  static const Color container = Color(0xFFD8AA34);
  static const Color profileSearch = Color(0xFF868686);
  static const Color profileContainer = Color(0xFF8A8A8A);
  static const Color hintText = Color(0xFF525252);
  static const Color dividerBorder = Color(0xFFE5E7EB);
}